// <auto-generated />
using AplikacjaDoNaukiJęzyków.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplikacjaDoNaukiJęzyków.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220522085229_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplikacjaDoNaukiJęzyków.Models.Slowo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PoziomSlowa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoAng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoAra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoPol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoUkr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Slowa");
                });
#pragma warning restore 612, 618
        }
    }
}
